// app/api/auth/[...nextauth]/route.ts
//
// Auth.js v5 catch-all handler — backs every /api/auth/* URL:
// signin, callback, signout, csrf, session, error. The handlers are
// generated by NextAuth() in lib/auth/index.ts and we re-export GET as-is.
//
// POST is wrapped: the credentials callback path (where the actual password
// check happens) gets an IP sliding-window limit (10 / 5 min) so brute-force
// guessing is bounded, and a failure-only audit-log write so we keep IP/UA
// for the request — events.signIn (lib/auth/index.ts) only fires on
// *success* and has no req to read.
//
// Edge runtime is required because the full config uses getRequestContext()
// to reach the D1 binding, which only exists inside the Pages worker.

import { getRequestContext } from "@cloudflare/next-on-pages";

import { ApiErrors, toErrorResponse } from "@/lib/api/errors";
import {
  checkLimit,
  getClientIp,
  RateLimitPolicies,
} from "@/lib/api/rate-limit";
import { logAudit } from "@/lib/audit/log";
import type { DbEnv } from "@/lib/db/client";

export const runtime = "edge";

export { GET } from "@/lib/auth/handlers";
import { POST as nextAuthPost } from "@/lib/auth/handlers";

const LOGIN_PATH_RE = /\/api\/auth\/callback\/credentials\/?$/;

/**
 * Auth.js redirects on the credentials callback: success → callbackUrl,
 * failure → /api/auth/signin?error=... (or /login?error= via our config).
 * Both responses are 302 with a Location header. We peek at it to decide
 * whether to audit-log a failure.
 */
function isLoginFailureRedirect(res: Response): boolean {
  if (res.status !== 302) return false;
  const location = res.headers.get("location");
  if (!location) return false;
  return /[?&]error=/.test(location);
}

export async function POST(req: Request): Promise<Response> {
  const isLogin = LOGIN_PATH_RE.test(new URL(req.url).pathname);

  if (isLogin) {
    const env = getRequestContext().env as unknown as DbEnv;
    const policy = RateLimitPolicies.loginByIp(getClientIp(req));
    const result = await checkLimit({
      db: env.DB,
      key: policy.key,
      limit: policy.limit,
      windowMs: policy.windowMs,
    });
    if (!result.ok) {
      // Reuse the unified error envelope from lib/api/errors so login 429s
      // match presign/share-create 429s — clients can pattern-match on
      // `error.code === 'rate_limited'` regardless of endpoint.
      const requestId = crypto.randomUUID();
      // Rate-limit denial is also worth auditing — the failed attempt never
      // reached `authorize`, so no events.signIn would fire either way.
      await logAudit({
        userId: null,
        op: "auth.login",
        status: "failure",
        errorMsg: "rate_limited",
        req,
      });
      return toErrorResponse(
        ApiErrors.rateLimitedWithRetry(
          result.retryAfter ?? 1,
          { policy: policy.key },
          "Too many login attempts. Try again later.",
        ),
        requestId,
      );
    }
  }

  // NextAuth v5 POST signature accepts NextRequest only; the standard
  // Request shape we receive is structurally compatible.
  const res = await nextAuthPost(
    req as unknown as Parameters<typeof nextAuthPost>[0],
  );

  if (isLogin && isLoginFailureRedirect(res)) {
    // authorize() returned null — we have req but no user. The companion
    // success path is handled by events.signIn in lib/auth/index.ts, which
    // does have a userId.
    await logAudit({
      userId: null,
      op: "auth.login",
      status: "failure",
      errorMsg: "invalid_credentials",
      req,
    });
  }

  return res;
}
