// app/api/auth/[...nextauth]/route.ts
//
// Auth.js v5 catch-all handler — backs every /api/auth/* URL:
// signin, callback, signout, csrf, session, error. The handlers are
// generated by NextAuth() in lib/auth/index.ts and we re-export GET as-is.
//
// POST is wrapped: the credentials callback path (where the actual password
// check happens) gets an IP sliding-window limit (10 / 5 min) so brute-force
// guessing is bounded. Other POST sub-paths (signout, CSRF token rotation,
// provider redirects) stay unthrottled — the limit is per-IP-per-bucket,
// and sharing a bucket with signout would let a single tab's logout block
// a legitimate user from logging back in.
//
// Edge runtime is required because the full config uses getRequestContext()
// to reach the D1 binding, which only exists inside the Pages worker.

import { getRequestContext } from "@cloudflare/next-on-pages";

import { ApiErrors, toErrorResponse } from "@/lib/api/errors";
import {
  checkLimit,
  getClientIp,
  RateLimitPolicies,
} from "@/lib/api/rate-limit";
import type { DbEnv } from "@/lib/db/client";

export const runtime = "edge";

export { GET } from "@/lib/auth/handlers";
import { POST as nextAuthPost } from "@/lib/auth/handlers";

const LOGIN_PATH_RE = /\/api\/auth\/callback\/credentials\/?$/;

export async function POST(req: Request): Promise<Response> {
  if (LOGIN_PATH_RE.test(new URL(req.url).pathname)) {
    const env = getRequestContext().env as unknown as DbEnv;
    const policy = RateLimitPolicies.loginByIp(getClientIp(req));
    const result = await checkLimit({
      db: env.DB,
      key: policy.key,
      limit: policy.limit,
      windowMs: policy.windowMs,
    });
    if (!result.ok) {
      // Reuse the unified error envelope from lib/api/errors so login 429s
      // match presign/share-create 429s — clients can pattern-match on
      // `error.code === 'rate_limited'` regardless of endpoint.
      const requestId = crypto.randomUUID();
      return toErrorResponse(
        ApiErrors.rateLimitedWithRetry(
          result.retryAfter ?? 1,
          { policy: policy.key },
          "Too many login attempts. Try again later.",
        ),
        requestId,
      );
    }
  }
  // NextAuth v5 POST signature accepts NextRequest only; the standard
  // Request shape we receive is structurally compatible.
  return nextAuthPost(req as unknown as Parameters<typeof nextAuthPost>[0]);
}
