// app/api/auth/[...nextauth]/route.ts
//
// Auth.js v5 catch-all handler — backs every /api/auth/* URL:
// signin, callback, signout, csrf, session, error. The handlers are
// generated by NextAuth() in lib/auth/index.ts and exported as is.
//
// Edge runtime is required because the full config uses getRequestContext()
// to reach the D1 binding, which only exists inside the Pages worker.

export const runtime = "edge";

export { GET, POST } from "@/lib/auth/handlers";
