allowBuilds:
  better-sqlite3: false
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

patchedDependencies:
  "@aws-sdk/xml-builder@3.972.24": "patches/@aws-sdk__xml-builder@3.972.24.patch"
